"""Jamf deployment artifacts generated from config (single source of truth).

* ``sudoers(cfg)``: an /etc/sudoers.d fragment granting the service account
  exactly the privileged commands surgic issues. Arguments are literal, except
  numeric PIDs / pf tokens, which use anchored regexes (sudo >= 1.9.10) so no
  extra flags can be appended (a glob ``*`` would also match ``-X 1 -d``).
* ``pf_rules(cfg)``: the rendered pf ruleset for a root-owned Jamf package
  (pair with ``network.pf_rules_managed = true``).
* ``allowed(cmd, cfg)``: sudoers-style matcher used by tests to prove
  every root command surgic runs is covered by the generated allowlist.
"""
from __future__ import annotations

import re

from .env import PRIVILEGED, egress_audit, firewall

_SUDOERS_SPECIAL = re.compile(r"([\\,:=])")
_RX_META = re.compile(r"([.^$*+?()\[\]{}|\\])")
NUM = "<NUM>"


def _esc(arg: str) -> str:
    """Escape characters sudoers treats specially in command arguments."""
    return _SUDOERS_SPECIAL.sub(r"\\\1", arg)


def privileged_commands(cfg) -> list[list[str]]:
    """Every root command line surgic can issue for this config. ``NUM`` marks
    a single numeric argument (PIDs, pf tokens)."""
    net, st = cfg.network, cfg.storage
    rules = firewall.RULES_PATH
    egress = f"{net.capture_dir}/egress_audit.pcap"
    blocked = f"{net.capture_dir}/pflog_blocked.pcap"
    cmds = [
        ["pfctl", "-s", "info"],
        ["pfctl", "-s", "rules"],
        ["pfctl", "-s", "Interfaces", "-v"],
        ["pfctl", "-n", "-f", rules],
        ["pfctl", "-f", rules],
        ["pfctl", "-E"],
        ["pfctl", "-f", firewall.SYSTEM_PF_CONF],
        ["pfctl", "-X", NUM],
        ["ifconfig", "pflog0", "create"],
        ["tcpdump", "-U", "-n", "-i", "any", "-w", egress, egress_audit.egress_filter(net.smb_share_ip)],
        ["tcpdump", "-U", "-n", "-i", "pflog0", "-w", blocked],
        ["kill", "-INT", NUM],
        ["mdutil", "-i", "off", st.ramdisk_mount],
        ["lsof", "-nP", "-iTCP", "-sTCP:LISTEN", "-iUDP"],
        ["profiles", "show", "-type", "configuration"],
    ]
    if not net.pf_rules_managed:
        cmds.append(["tee", rules])
    return cmds


def _line(cmd: list[str]) -> str:
    if NUM in cmd:
        # Anchored regex over the whole argument string: exactly these args.
        args = " ".join("[0-9]+" if a == NUM else _RX_META.sub(r"\\\1", a) for a in cmd[1:])
        return f"{PRIVILEGED[cmd[0]]} ^{_esc(args)}$"
    return " ".join([PRIVILEGED[cmd[0]], *(_esc(a) for a in cmd[1:])])


def sudoers(cfg) -> str:
    user = cfg.jamf.service_user
    if not re.fullmatch(r"[a-z_][a-z0-9_-]{0,31}", user):
        raise ValueError("invalid service_user")
    lines = [_line(c) for c in privileged_commands(cfg)]
    body = ", \\\n    ".join(lines)
    return (
        "# /etc/sudoers.d/surgic -- generated by `surgic jamf sudoers`; deploy via Jamf.\n"
        "# Grants ONLY the exact privileged commands surgic issues. Regenerate on config change.\n"
        f"Cmnd_Alias SURGIC_CMDS = \\\n    {body}\n"
        f"Defaults:{user} !requiretty, !lecture, env_reset\n"
        f"{user} ALL = (root) NOPASSWD: SURGIC_CMDS\n"
    )


def pf_rules(cfg) -> str:
    return firewall.render(cfg.network.smb_share_ip)


def allowed(cmd: list[str], cfg) -> bool:
    """Would the generated sudoers allow this root command (as issued by Runner)?"""
    if not cmd or not cmd[0].startswith("/"):
        return False
    for spec in privileged_commands(cfg):
        if PRIVILEGED[spec[0]] != cmd[0] or len(spec) != len(cmd):
            continue
        if all(p == a or (p == NUM and a.isdigit()) for p, a in zip(spec[1:], cmd[1:])):
            return True
    return False
